CREATE TABLE candidate_qualification(
  id int(11) NOT NULL,
  candidate_id int(11) NOT NULL,
  diploma int (1) DEFAULT 0,
  degree_name varchar(10) NOT NULL,
  is_degree_name_verified int (1) DEFAULT 0,
  employee_decipline varchar(100) NOT NULL,
  is_employee_decipline_verified int (1) DEFAULT 0,
  passing_year int(11) NOT NULL,
  is_passing_year_verified int (1) DEFAULT 0,
  aggr_per double DEFAULT NULL,
  final_year_per double DEFAULT NULL,
  is_final_year_per_verified int (1) DEFAULT 0,
  training_institute varchar(20) NOT NULL,
  is_training_institute_verified int (1) DEFAULT 0,
  training_duration_month int(3) DEFAULT NULL,
  is_training_duration_month_verified int (1) DEFAULT 0,
  other_training varchar(255) DEFAULT NULL,
  is_other_training_verified int (1) DEFAULT 0,
  creator_stamp datetime DEFAULT NULL,
  creator_user int(11) DEFAULT NULL,
    KEY `FK_candidate_qual_candidate_id` (`candidate_id`),
  CONSTRAINT `FK_candidate_qual_candidate_id` FOREIGN KEY (`candidate_id`) REFERENCES `fellowship_candidates` (`id`),
 PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8; 